name: 30 Day Auto Post
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Libs
        run: pip install -r requirements.txt
      - name: Run Blogger Bot
        env:
          BLOG_ID: 1647802080466447812
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.BLOGGER_REFRESH_TOKEN }}
        run: python main.py
      - name: Save Update
        run: |
          git config user.name "bot"
          git config user.email "bot@bot.com"
          git add .
          git commit -m "auto update" || true
          git push
