name: Daily Quiz Auto Generator
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install gTTS
        run: pip install -r requirements.txt
      - name: Run Quiz Generator
        run: python main.py
        env:
          BLOGGER_ID: ${{ secrets.BLOGGER_ID }}
          BLOGGER_TOKEN: ${{ secrets.BLOGGER_TOKEN }}
      - name: Commit files
        run: |
          git config user.name "bot"
          git config user.email "bot@bot.com"
          git add .
          git commit -m "update" || true
          git push
